# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: a.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x07\x61.proto\x12\x05proto"\xc2\x02\n\x1a\x43SGetPlayerPersonalShowRes\x12"\n\x07players\x18\x01 \x03(\x0b\x32\x11.proto.PlayerInfo[...]')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CSGETPLAYERPERSONALSHOWRES']._serialized_start=19
  _globals['_CSGETPLAYERPERSONALSHOWRES']._serialized_end=341
  _globals['_PLAYERINFO']._serialized_start=344
  _globals['_PLAYERINFO']._serialized_end=1083
  _globals['_CLANTAG']._serialized_start=1085
  _globals['_CLANTAG']._serialized_end=1159
  _globals['_PREMIUMFEATURES']._serialized_start=1161
  _globals['_PREMIUMFEATURES']._serialized_end=1223
  _globals['_STATENTRY']._serialized_start=1225
  _globals['_STATENTRY']._serialized_end=1303
  _globals['_STATDETAIL']._serialized_start=1305
  _globals['_STATDETAIL']._serialized_end=1409
  _globals['_RECENTACTIVITY']._serialized_start=1411
  _globals['_RECENTACTIVITY']._serialized_end=1466
  _globals['_ACTIVITYENTRY']._serialized_start=1468
  _globals['_ACTIVITYENTRY']._serialized_end=1540
  _globals['_STATUSINDICATOR']._serialized_start=1542
  _globals['_STATUSINDICATOR']._serialized_end=1602
  _globals['_INVENTORY']._serialized_start=1605
  _globals['_INVENTORY']._serialized_end=1802
  _globals['_INVENTORYITEM']._serialized_start=1804
  _globals['_INVENTORYITEM']._serialized_end=1906
  _globals['_CLANINFO']._serialized_start=1909
  _globals['_CLANINFO']._serialized_end=2043
  _globals['_ACHIEVEMENT']._serialized_start=2046
  _globals['_ACHIEVEMENT']._serialized_end=2183
  _globals['_PLAYERSTATUS']._serialized_start=2186
  _globals['_PLAYERSTATUS']._serialized_end=2333
  _globals['_CURRENCY']._serialized_start=2335
  _globals['_CURRENCY']._serialized_end=2360
  _globals['_TIMELIMITEDEVENT']._serialized_start=2362
  _globals['_TIMELIMITEDEVENT']._serialized_end=2480
# @@protoc_insertion_point(module_scope)
