# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: back.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



import basics_pb2 as basics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nback.proto\x12\x05proto\x1a\x0c\x62\x61sics.proto"\xd3\x01\n\x13GetAccountFreshInfo\x12\x13\n\x06\x66ield1\x18\x01 \x01(\x05H\x00\x[...]')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'back_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEMSTATUS']._serialized_start=2354
  _globals['_ITEMSTATUS']._serialized_end=2420
  _globals['_ITEMTYPE']._serialized_start=2423
  _globals['_ITEMTYPE']._serialized_end=2964
  _globals['_ITEMSUBTYPE']._serialized_start=2967
  _globals['_ITEMSUBTYPE']._serialized_end=4915
  _globals['_GETACCOUNTFRESHINFO']._serialized_start=36
  _globals['_GETACCOUNTFRESHINFO']._serialized_end=247
  _globals['_FRESHREWARD']._serialized_start=250
  _globals['_FRESHREWARD']._serialized_end=452
  _globals['_REWARDDETAIL']._serialized_start=454
  _globals['_REWARDEXTRA']._serialized_start=536
  _globals['_REWARDEXTRA']._serialized_end=643
  _globals['_GRANDMASTERPOSITION']._serialized_start=645
  _globals['_GRANDMASTERPOSITION']._serialized_end=714
  _globals['_GETCSRANKINGMATCHGRANDMASTERPOSITIONSRESPONSE']._serialized_start=716
  _globals['_GETCSRANKINGMATCHGRANDMASTERPOSITIONSRESPONSE']._serialized_end=810
  _globals['_CSGETBACKPACKRES']._serialized_start=813
  _globals['_CSGETBACKPACKRES']._serialized_end=1246
  _globals['_ACCOUNTWALLET']._serialized_start=1248
  _globals['_ACCOUNTWALLET']._serialized_end=1356
  _globals['_ITEM']._serialized_start=1359
  _globals['_ITEM']._serialized_end=1704
  _globals['_MAXLOBBYDISPLAYINFO']._serialized_start=1706
  _globals['_MAXLOBBYDISPLAYINFO']._serialized_end=1820
  _globals['_PERMANENTVALUEITEM']._serialized_start=1822
  _globals['_PERMANENTVALUEITEM']._serialized_end=1879
  _globals['_WEAPONSKINSTAT']._serialized_start=1882
  _globals['_WEAPONSKINSTAT']._serialized_end=2081
  _globals['_ACCOUNTCOINSOUTGAME']._serialized_start=2083
  _globals['_ACCOUNTCOINSOUTGAME']._serialized_end=2153
  _globals['_WEAPONSKINCUSTOM']._serialized_start=2156
  _globals['_WEAPONSKINCUSTOM']._serialized_end=2307
  _globals['_PUINT32KEYVAL']._serialized_start=2309
  _globals['_PUINT32KEYVAL']._serialized_end=2352
# @@protoc_insertion_point(module_scope)
